# Generated by Django 2.1.2 on 2019-08-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
