# Generated by Django 2.1.2 on 2019-08-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_goods_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.CharField(max_length=32)),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_oprice', models.CharField(max_length=32)),
                ('goods_cprice', models.CharField(max_length=32)),
                ('goods_kucun', models.CharField(max_length=32)),
                ('goods_desc', models.CharField(max_length=100)),
                ('goods_detail', models.TextField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Goods_Type')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_address', models.CharField(max_length=64)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Goods')),
            ],
        ),
    ]
