# Generated by Django 2.1.2 on 2019-08-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_goods_goodsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouXiang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
