# Generated by Django 2.1.2 on 2019-08-23 01:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_touxiang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
