# Generated by Django 2.1.2 on 2019-08-26 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField()),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_picture', models.CharField(max_length=64)),
                ('goods_price', models.IntegerField()),
                ('goods_num', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer')),
            ],
        ),
    ]
